import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import tailwindcss from '@tailwindcss/vite';

import mdx from '@astrojs/mdx';
import starlightLinksValidator from 'starlight-links-validator';
import starlightBlog from 'starlight-blog';
import starlightImageZoom from 'starlight-image-zoom';
import starlightHeadingBadges from 'starlight-heading-badges';
import starlightGiscus from 'starlight-giscus';
import { unified } from '@astrojs/markdown-remark';
import astroEmbed from 'astro-embed/integration';

import partytown from '@astrojs/partytown';

// Локальная интеграция вместо ручного подключения компонента на каждой
// странице: injectScript('head-inline', ...) вставляет скрипт в <head>
// абсолютно всех страниц на этапе сборки — и Starlight-документации, и
// самостоятельных .astro-страниц (лендинг, privacy/terms/license, 404),
// у которых нет общего лейаута. Новый счётчик добавлять сюда же ещё
// одним injectScript-вызовом — трогать страницы не придётся.
// Ограничение: injectScript принимает только JS, поэтому <noscript>-пиксель
// (fallback для отключённого JS) сюда не переносится — доля такого трафика
// пренебрежимо мала, и сам Яндекс считает noscript-пиксель необязательным.
function analyticsIntegration() {
  return {
    name: 'analytics',
    hooks: {
      'astro:config:setup': ({ injectScript }) => {
        injectScript(
          'head-inline',
          `
          (function(m,e,t,r,i,k,a){
              m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
              k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
          })(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=110603764', 'ym');

          ym(110603764, 'init', {ssr:true, webvisor:true, clickmap:true, ecommerce:"dataLayer", referrer: document.referrer, url: location.href, accurateTrackBounce:true, trackLinks:true});
          `,
        );
      },
    },
  };
}

// https://starlight.astro.build/
export default defineConfig({
  site: 'https://doc.pathofstrategy.com',

  // Старые кириллические URL глав (до перехода на латинские слаги) —
  // сохраняем как редиректы ради ранее опубликованных/проиндексированных ссылок.
  redirects: {
    '/texts/guy-guy-tszy/gl-01-открытость-и-закрытость': '/texts/guy-guy-tszy/gl-01-otkrytost-i-zakrytost',
    '/texts/guy-guy-tszy/gl-02-несходство-и-сходство': '/texts/guy-guy-tszy/gl-02-neshodstvo-i-shodstvo',
    '/texts/guy-guy-tszy/gl-03-зацепка-внутри': '/texts/guy-guy-tszy/gl-03-zatsepka-vnutri',
    '/texts/guy-guy-tszy/gl-04-упреждать-появление-оврагов': '/texts/guy-guy-tszy/gl-04-uprezhdat-poyavlenie-ovragov',
    '/texts/guy-guy-tszy/gl-05-воодушевлять-чтобы-подчинить': '/texts/guy-guy-tszy/gl-05-voodushevlyat-chtoby-podchinit',
    '/texts/guy-guy-tszy/gl-06-противостояние-в-согласии': '/texts/guy-guy-tszy/gl-06-protivostoyanie-v-soglasii',
    '/texts/guy-guy-tszy/gl-07-о-проницательности': '/texts/guy-guy-tszy/gl-07-o-pronitsatelnosti',
    '/texts/guy-guy-tszy/gl-08-угождение': '/texts/guy-guy-tszy/gl-08-ugozhdenie',
    '/texts/guy-guy-tszy/gl-09-оселок-разговора': '/texts/guy-guy-tszy/gl-09-oselok-razgovora',
    '/texts/guy-guy-tszy/gl-10-планы': '/texts/guy-guy-tszy/gl-10-plany',
    '/texts/guy-guy-tszy/gl-11-принятие-решений': '/texts/guy-guy-tszy/gl-11-prinyatie-resheniy',
    '/texts/guy-guy-tszy/gl-12-о-соответствии-слов-делам': '/texts/guy-guy-tszy/gl-12-o-sootvetstvii-slov-delam',
    '/texts/liu-tao/gl-01-учитель-правителя-вэнь': '/texts/liu-tao/gl-01-uchitel-pravitelya-ven',
    '/texts/liu-tao/gl-02-полнота-и-пустота': '/texts/liu-tao/gl-02-polnota-i-pustota',
    '/texts/liu-tao/gl-03-дела-государства': '/texts/liu-tao/gl-03-dela-gosudarstva',
    '/texts/liu-tao/gl-04-великие-правила-этикета': '/texts/liu-tao/gl-04-velikie-pravila-etiketa',
    '/texts/liu-tao/gl-05-ясные-указания': '/texts/liu-tao/gl-05-yasnye-ukazaniya',
    '/texts/liu-tao/gl-06-шесть-хранителей': '/texts/liu-tao/gl-06-shest-hraniteley',
    '/texts/liu-tao/gl-07-сохранение-территории-государства': '/texts/liu-tao/gl-07-sohranenie-territorii-gosudarstva',
    '/texts/liu-tao/gl-08-сохранение-государства': '/texts/liu-tao/gl-08-sohranenie-gosudarstva',
    '/texts/liu-tao/gl-09-почитание-достойных': '/texts/liu-tao/gl-09-pochitanie-dostoynyh',
    '/texts/liu-tao/gl-10-выдвижение-достойных': '/texts/liu-tao/gl-10-vydvizhenie-dostoynyh',
    '/texts/liu-tao/gl-11-награды-и-наказания': '/texts/liu-tao/gl-11-nagrady-i-nakazaniya',
    '/texts/liu-tao/gl-12-дао-войны': '/texts/liu-tao/gl-12-dao-voyny',
    '/texts/liu-tao/gl-13-начальные-наставления': '/texts/liu-tao/gl-13-nachalnye-nastavleniya',
    '/texts/liu-tao/gl-14-гражданские-наставления': '/texts/liu-tao/gl-14-grazhdanskie-nastavleniya',
    '/texts/liu-tao/gl-15-гражданское-наступление': '/texts/liu-tao/gl-15-grazhdanskoe-nastuplenie',
    '/texts/liu-tao/gl-16-наставление-о-согласии-с-людьми': '/texts/liu-tao/gl-16-nastavlenie-o-soglasii-s-lyudmi',
    '/texts/liu-tao/gl-17-три-сомнения': '/texts/liu-tao/gl-17-tri-somneniya',
    '/texts/liu-tao/gl-18-крылья-правителя': '/texts/liu-tao/gl-18-krylya-pravitelya',
    '/texts/liu-tao/gl-19-обсуждение-генералов': '/texts/liu-tao/gl-19-obsuzhdenie-generalov',
    '/texts/liu-tao/gl-20-отбор-командиров': '/texts/liu-tao/gl-20-otbor-komandirov',
    '/texts/liu-tao/gl-21-назначение-генерала': '/texts/liu-tao/gl-21-naznachenie-generala',
    '/texts/liu-tao/gl-22-воодушевление-армии': '/texts/liu-tao/gl-22-voodushevlenie-armii',
    '/texts/liu-tao/gl-23-секретные-бирки': '/texts/liu-tao/gl-23-sekretnye-birki',
    '/texts/liu-tao/gl-24-секретные-письма': '/texts/liu-tao/gl-24-sekretnye-pisma',
    '/texts/liu-tao/gl-25-стратегическая-сила-армии': '/texts/liu-tao/gl-25-strategicheskaya-sila-armii',
    '/texts/liu-tao/gl-26-необычная-армия': '/texts/liu-tao/gl-26-neobychnaya-armiya',
    '/texts/liu-tao/gl-27-пять-звуков': '/texts/liu-tao/gl-27-pyat-zvukov',
    '/texts/liu-tao/gl-28-признаки-армии': '/texts/liu-tao/gl-28-priznaki-armii',
    '/texts/liu-tao/gl-29-хозяйственные-принадлежности-и-утварь': '/texts/liu-tao/gl-29-hozyaystvennye-prinadlezhnosti-i-utvar',
    '/texts/liu-tao/gl-30-снаряжение-армии': '/texts/liu-tao/gl-30-snaryazhenie-armii',
    '/texts/liu-tao/gl-31-три-развертывания': '/texts/liu-tao/gl-31-tri-razvertyvaniya',
    '/texts/liu-tao/gl-32-безотлагательные-сражения': '/texts/liu-tao/gl-32-bezotlagatelnye-srazheniya',
    '/texts/liu-tao/gl-33-решительное-отступление': '/texts/liu-tao/gl-33-reshitelnoe-otstuplenie',
    '/texts/liu-tao/gl-34-планирование-для-армии': '/texts/liu-tao/gl-34-planirovanie-dlya-armii',
    '/texts/liu-tao/gl-35-приближение-к-границе': '/texts/liu-tao/gl-35-priblizhenie-k-granitse',
    '/texts/liu-tao/gl-36-движение-и-отдых': '/texts/liu-tao/gl-36-dvizhenie-i-otdyh',
    '/texts/liu-tao/gl-37-гонги-и-барабаны': '/texts/liu-tao/gl-37-gongi-i-barabany',
    '/texts/liu-tao/gl-38-отрезанные-пути': '/texts/liu-tao/gl-38-otrezannye-puti',
    '/texts/liu-tao/gl-39-захват-вражеской-территории': '/texts/liu-tao/gl-39-zahvat-vrazheskoy-territorii',
    '/texts/liu-tao/gl-40-огневая-война': '/texts/liu-tao/gl-40-ognevaya-voyna',
    '/texts/liu-tao/gl-41-пустые-укрепления': '/texts/liu-tao/gl-41-pustye-ukrepleniya',
    '/texts/liu-tao/gl-42-война-в-лесу': '/texts/liu-tao/gl-42-voyna-v-lesu',
    '/texts/liu-tao/gl-43-бурная-и-быстрая-сила': '/texts/liu-tao/gl-43-burnaya-i-bystraya-sila',
    '/texts/liu-tao/gl-44-сильный-враг': '/texts/liu-tao/gl-44-silnyy-vrag',
    '/texts/liu-tao/gl-45-воинственный-враг': '/texts/liu-tao/gl-45-voinstvennyy-vrag',
    '/texts/liu-tao/gl-46-боевые-порядки-вороны-и-облака-в-горах': '/texts/liu-tao/gl-46-boevye-poryadki-vorony-i-oblaka-v-gorah',
    '/texts/liu-tao/gl-47-боевые-порядки-вороны-и-облака-в-болоте': '/texts/liu-tao/gl-47-boevye-poryadki-vorony-i-oblaka-v-bolote',
    '/texts/liu-tao/gl-48-малые-и-большие': '/texts/liu-tao/gl-48-malye-i-bolshie',
    '/texts/liu-tao/gl-49-разделение-долины': '/texts/liu-tao/gl-49-razdelenie-doliny',
    '/texts/liu-tao/gl-50-рассредоточение-и-соединение': '/texts/liu-tao/gl-50-rassredotochenie-i-soedinenie',
    '/texts/liu-tao/gl-51-боевой-головной-отряд': '/texts/liu-tao/gl-51-boevoy-golovnoy-otryad',
    '/texts/liu-tao/gl-52-отбор-воинов': '/texts/liu-tao/gl-52-otbor-voinov',
    '/texts/liu-tao/gl-53-обучение-бою': '/texts/liu-tao/gl-53-obuchenie-boyu',
    '/texts/liu-tao/gl-54-равные-силы': '/texts/liu-tao/gl-54-ravnye-sily',
    '/texts/liu-tao/gl-55-воины-на-боевых-колесницах': '/texts/liu-tao/gl-55-voiny-na-boevyh-kolesnitsah',
    '/texts/liu-tao/gl-56-воины-боевой-конницы': '/texts/liu-tao/gl-56-voiny-boevoy-konnitsy',
    '/texts/liu-tao/gl-57-колесницы-в-битве': '/texts/liu-tao/gl-57-kolesnitsy-v-bitve',
    '/texts/liu-tao/gl-58-конница-в-битве': '/texts/liu-tao/gl-58-konnitsa-v-bitve',
    '/texts/liu-tao/gl-59-пешие-воины-в-битве': '/texts/liu-tao/gl-59-peshie-voiny-v-bitve',
    '/texts/wei-liao-zi/gl-01-небесные-чиновники': '/texts/wei-liao-zi/gl-01-nebesnye-chinovniki',
    '/texts/wei-liao-zi/gl-02-рассуждения-о-войске': '/texts/wei-liao-zi/gl-02-rassuzhdeniya-o-voyske',
    '/texts/wei-liao-zi/gl-03-установление-порядка': '/texts/wei-liao-zi/gl-03-ustanovlenie-poryadka',
    '/texts/wei-liao-zi/gl-04-боевая-мощь': '/texts/wei-liao-zi/gl-04-boevaya-moshch',
    '/texts/wei-liao-zi/gl-05-искусство-нападения': '/texts/wei-liao-zi/gl-05-iskusstvo-napadeniya',
    '/texts/wei-liao-zi/gl-06-искусство-обороны': '/texts/wei-liao-zi/gl-06-iskusstvo-oborony',
    '/texts/wei-liao-zi/gl-07-двенадцать-заслуг-и-бед': '/texts/wei-liao-zi/gl-07-dvenadtsat-zaslug-i-bed',
    '/texts/wei-liao-zi/gl-08-военные-обсуждения': '/texts/wei-liao-zi/gl-08-voennye-obsuzhdeniya',
    '/texts/wei-liao-zi/gl-09-судья-полководец': '/texts/wei-liao-zi/gl-09-sudya-polkovodets',
    '/texts/wei-liao-zi/gl-10-изначальные-чиновники': '/texts/wei-liao-zi/gl-10-iznachalnye-chinovniki',
    '/texts/wei-liao-zi/gl-11-управление-корнем': '/texts/wei-liao-zi/gl-11-upravlenie-kornem',
    '/texts/wei-liao-zi/gl-12-право-войны': '/texts/wei-liao-zi/gl-12-pravo-voyny',
    '/texts/wei-liao-zi/gl-13-приказ-о-тяжёлом-наказании': '/texts/wei-liao-zi/gl-13-prikaz-o-tyazhelom-nakazanii',
    '/texts/wei-liao-zi/gl-14-приказ-о-порядках-у-и-ши': '/texts/wei-liao-zi/gl-14-prikaz-o-poryadkah-u-i-shi',
    '/texts/wei-liao-zi/gl-15-приказ-о-разделении-лагерей': '/texts/wei-liao-zi/gl-15-prikaz-o-razdelenii-lagerey',
    '/texts/wei-liao-zi/gl-16-приказ-о-связывании-у': '/texts/wei-liao-zi/gl-16-prikaz-o-svyazyvanii-u',
    '/texts/wei-liao-zi/gl-17-приказ-о-классификации-войск': '/texts/wei-liao-zi/gl-17-prikaz-o-klassifikatsii-voysk',
    '/texts/wei-liao-zi/gl-18-приказ-о-барабанах-и-трубах': '/texts/wei-liao-zi/gl-18-prikaz-o-barabanah-i-trubah',
    '/texts/wei-liao-zi/gl-19-приказ-полководца': '/texts/wei-liao-zi/gl-19-prikaz-polkovodtsa',
    '/texts/wei-liao-zi/gl-20-приказ-о-пяточной-армии': '/texts/wei-liao-zi/gl-20-prikaz-o-pyatochnoy-armii',
    '/texts/wei-liao-zi/gl-21-военное-обучение-верхняя-часть': '/texts/wei-liao-zi/gl-21-voennoe-obuchenie-verhnyaya-chast',
    '/texts/wei-liao-zi/gl-22-военное-обучение-нижняя-часть': '/texts/wei-liao-zi/gl-22-voennoe-obuchenie-nizhnyaya-chast',
    '/texts/wei-liao-zi/gl-23-военные-приказы-верхняя-часть': '/texts/wei-liao-zi/gl-23-voennye-prikazy-verhnyaya-chast',
    '/texts/wei-liao-zi/gl-24-военные-приказы-нижняя-часть': '/texts/wei-liao-zi/gl-24-voennye-prikazy-nizhnyaya-chast',

    // Автор блога "Редакция" переименован в латинский псевдоним Tzuin —
    // slug страницы автора (starlight-blog) генерируется из name через
    // github-slugger, который кириллицу не транслитерирует.
    '/blog/authors/редакция': '/blog/authors/tzuin',
    '/en/blog/authors/редакция': '/en/blog/authors/tzuin',
  },


  // Astro 7 переключил markdown-процессор по умолчанию на Sätteri, который
  // пока не поддерживается плагином starlight-image-zoom. Возвращаем
  // прежний процессор unified(), пока плагин не добавит поддержку:
  // https://github.com/HiDeoo/starlight-image-zoom/issues/63
  markdown: {
    processor: unified(),
  },

  integrations: [starlight({
    title: { ru: 'Путь Стратегии', en: 'Path of Strategy' },
    description: 'Система древнекитайских классических текстов',
    disable404Route: true,
    plugins: [
      // starlightLinksValidator({ errorOnInvalidLinks: false }),
      starlightBlog({
        title: { ru: 'Заметки', en: 'Notes' },
        authors: {
          gate: {
            name: 'Tzuin',
            title: 'Путь Стратегии',
            url: 'https://doc.pathofstrategy.com',
            picture: '/favicon.svg'
          }
        }
      }),
      starlightImageZoom(),
      starlightHeadingBadges(),
      starlightGiscus({
        repo: 'great-foundation-pro/doc-pathofstrategy',
        repoId: 'R_kgDOS0ltZw',
        category: 'General',
        categoryId: 'DIC_kwDOS0ltZ84DA0lJ',
        // Кастомная чёрно-белая тема «Путь Стратегии» (public/giscus-theme.css).
        // giscus.app сам делает fetch() этого файла из своего iframe. Раздача
        // с doc.pathofstrategy.com (nginx/Coolify) не отправляет заголовок
        // Access-Control-Allow-Origin — кросс-доменный fetch падает по CORS,
        // и giscus молча откатывается на свою тему по умолчанию, которая
        // следует системной prefers-color-scheme браузера (а не теме сайта).
        // jsDelivr зеркалит файл прямо из GitHub-репозитория и отдаёт его
        // с Access-Control-Allow-Origin: * и правильным Content-Type: text/css —
        // проверено вручную, тема применяется стабильно независимо от темы ОС.
        // Нюанс: jsDelivr кэширует @master несколько часов — после правок
        // giscus-theme.css нужно запушить в GitHub и при необходимости
        // сбросить кэш через https://purge.jsdelivr.net/gh/great-foundation-pro/doc-pathofstrategy@master/public/giscus-theme.css
        theme: {
          light: 'https://cdn.jsdelivr.net/gh/great-foundation-pro/doc-pathofstrategy@master/public/giscus-theme.css',
          dark: 'https://cdn.jsdelivr.net/gh/great-foundation-pro/doc-pathofstrategy@master/public/giscus-theme.css',
          auto: 'https://cdn.jsdelivr.net/gh/great-foundation-pro/doc-pathofstrategy@master/public/giscus-theme.css',
        },
      }),
    ],
    customCss: [
      './src/styles/custom.css',
    ],
    head: [],
    components: {
      ThemeProvider: './src/components/ThemeProvider.astro',
      ThemeSelect: './src/components/HeaderThemeSelect.astro',
      SocialIcons: './src/components/HeaderSocialIcons.astro',
      Head: './src/components/Head.astro',
      SiteTitle: './src/components/SiteTitle.astro',
    },
    defaultLocale: 'root',
    locales: {
      root: {
        label: 'Русский',
        lang: 'ru',
      },
      en: {
        label: 'English',
        lang: 'en',
      },
    },
    sidebar: [
      {
        label: 'О проекте', translations: { en: 'About' },
          collapsed: true,
        items: [
          { label: 'Введение', translations: { en: 'Introduction' }, link: '/introduction' },
          { label: 'О проекте', translations: { en: 'About' }, link: '/about' },
        ],
      },
      {
        label: 'Сунь-Цзы', translations: { en: 'Sun Tzu' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/sunzi' },
          { label: 'Комментарии', translations: { en: 'Commentary' }, link: '/texts/sunzi/gl-00-kommentarii' },
          { label: 'I. Предварительные расчёты', link: '/texts/sunzi/gl-01-predvaritelnye-raschety' },
          { label: 'II. Ведение войны', link: '/texts/sunzi/gl-02-vedenie-voyny' },
          { label: 'III. Стратегическое нападение', link: '/texts/sunzi/gl-03-strategicheskoe-napadenie' },
          { label: 'IV. Форма', link: '/texts/sunzi/gl-04-forma' },
          { label: 'V. Мощь', link: '/texts/sunzi/gl-05-moshch' },
          { label: 'VI. Полнота и пустота', link: '/texts/sunzi/gl-06-polnita-i-pustota' },
          { label: 'VII. Борьба на войне', link: '/texts/sunzi/gl-07-borba-na-voyne' },
          { label: 'VIII. Девять изменений', link: '/texts/sunzi/gl-08-devyat-izmeneniy' },
          { label: 'IX. Поход', link: '/texts/sunzi/gl-09-pohod' },
          { label: 'X. Формы местности', link: '/texts/sunzi/gl-10-formy-mestnosti' },
          { label: 'XI. Девять местностей', link: '/texts/sunzi/gl-11-devyat-mestnostey' },
          { label: 'XII. Огневое нападение', link: '/texts/sunzi/gl-12-ognevoie-napadenie' },
          { label: 'XIII. Использование шпионов', link: '/texts/sunzi/gl-13-ispolzovanie-shpionov' },
        ],
      },
      {
        label: 'Вэй Ляо-цзы', translations: { en: 'Wei Liaozi' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/wei-liao-zi' },
          { label: 'I. Небесные чиновники', link: '/texts/wei-liao-zi/gl-01-nebesnye-chinovniki' },
          { label: 'II. Рассуждения о войске', link: '/texts/wei-liao-zi/gl-02-rassuzhdeniya-o-voyske' },
          { label: 'III. Установление порядка', link: '/texts/wei-liao-zi/gl-03-ustanovlenie-poryadka' },
          { label: 'IV. Боевая мощь', link: '/texts/wei-liao-zi/gl-04-boevaya-moshch' },
          { label: 'V. Искусство нападения', link: '/texts/wei-liao-zi/gl-05-iskusstvo-napadeniya' },
          { label: 'VI. Искусство обороны', link: '/texts/wei-liao-zi/gl-06-iskusstvo-oborony' },
          { label: 'VII. Двенадцать заслуг и бед', link: '/texts/wei-liao-zi/gl-07-dvenadtsat-zaslug-i-bed' },
          { label: 'VIII. Военные обсуждения', link: '/texts/wei-liao-zi/gl-08-voennye-obsuzhdeniya' },
          { label: 'IX. Судья-полководец', link: '/texts/wei-liao-zi/gl-09-sudya-polkovodets' },
          { label: 'X. Изначальные чиновники', link: '/texts/wei-liao-zi/gl-10-iznachalnye-chinovniki' },
          { label: 'XI. Управление корнем', link: '/texts/wei-liao-zi/gl-11-upravlenie-kornem' },
          { label: 'XII. Право войны', link: '/texts/wei-liao-zi/gl-12-pravo-voyny' },
          { label: 'XIII. Приказ о тяжёлом наказании', link: '/texts/wei-liao-zi/gl-13-prikaz-o-tyazhelom-nakazanii' },
          { label: 'XIV. Приказ о порядках у и ши', link: '/texts/wei-liao-zi/gl-14-prikaz-o-poryadkah-u-i-shi' },
          { label: 'XV. Приказ о разделении лагерей', link: '/texts/wei-liao-zi/gl-15-prikaz-o-razdelenii-lagerey' },
          { label: 'XVI. Приказ о связывании у', link: '/texts/wei-liao-zi/gl-16-prikaz-o-svyazyvanii-u' },
          { label: 'XVII. Приказ о классификации войск', link: '/texts/wei-liao-zi/gl-17-prikaz-o-klassifikatsii-voysk' },
          { label: 'XVIII. Приказ о барабанах и трубах', link: '/texts/wei-liao-zi/gl-18-prikaz-o-barabanah-i-trubah' },
          { label: 'XIX. Приказ полководца', link: '/texts/wei-liao-zi/gl-19-prikaz-polkovodtsa' },
          { label: 'XX. Приказ о пяточной армии', link: '/texts/wei-liao-zi/gl-20-prikaz-o-pyatochnoy-armii' },
          { label: 'XXI. Военное обучение (верх)', link: '/texts/wei-liao-zi/gl-21-voennoe-obuchenie-verhnyaya-chast' },
          { label: 'XXII. Военное обучение (низ)', link: '/texts/wei-liao-zi/gl-22-voennoe-obuchenie-nizhnyaya-chast' },
          { label: 'XXIII. Военные приказы (верх)', link: '/texts/wei-liao-zi/gl-23-voennye-prikazy-verhnyaya-chast' },
          { label: 'XXIV. Военные приказы (низ)', link: '/texts/wei-liao-zi/gl-24-voennye-prikazy-nizhnyaya-chast' },
        ],
      },
      {
        label: 'Гуй Гу-цзы', translations: { en: 'Guiguzi' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/guy-guy-tszy' },
          { label: 'Комментарии', translations: { en: 'Commentary' }, link: '/texts/guy-guy-tszy/00-kommentarii' },
          { label: 'I. Открытость и закрытость', link: '/texts/guy-guy-tszy/gl-01-otkrytost-i-zakrytost' },
          { label: 'II. Несходство и сходство', link: '/texts/guy-guy-tszy/gl-02-neshodstvo-i-shodstvo' },
          { label: 'III. Зацепка внутри', link: '/texts/guy-guy-tszy/gl-03-zatsepka-vnutri' },
          { label: 'IV. Упреждать появление оврагов', link: '/texts/guy-guy-tszy/gl-04-uprezhdat-poyavlenie-ovragov' },
          { label: 'V. Воодушевлять, чтобы подчинить', link: '/texts/guy-guy-tszy/gl-05-voodushevlyat-chtoby-podchinit' },
          { label: 'VI. Противостояние в согласии', link: '/texts/guy-guy-tszy/gl-06-protivostoyanie-v-soglasii' },
          { label: 'VII. О проницательности', link: '/texts/guy-guy-tszy/gl-07-o-pronitsatelnosti' },
          { label: 'VIII. Угождение', link: '/texts/guy-guy-tszy/gl-08-ugozhdenie' },
          { label: 'IX. Оселок разговора', link: '/texts/guy-guy-tszy/gl-09-oselok-razgovora' },
          { label: 'X. Планы', link: '/texts/guy-guy-tszy/gl-10-plany' },
          { label: 'XI. Принятие решений', link: '/texts/guy-guy-tszy/gl-11-prinyatie-resheniy' },
          { label: 'XII. О соответствии слов делам', link: '/texts/guy-guy-tszy/gl-12-o-sootvetstvii-slov-delam' },
        ],
      },
      {
        label: 'Семь искусств', translations: { en: 'Seven Arts' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/sem-iskusstv' },
          { label: 'I. Восполнение духа', link: '/texts/sem-iskusstv/gl-01-vospolnenie-dukha' },
          { label: 'II. Пестование воли', link: '/texts/sem-iskusstv/gl-02-pestovanie-voli' },
          { label: 'III. Наполненность помыслов', link: '/texts/sem-iskusstv/gl-03-napolnennost-pomyslov' },
          { label: 'IV. Разделение силы', link: '/texts/sem-iskusstv/gl-04-razdelenie-sily' },
          { label: 'V. Распространение силы', link: '/texts/sem-iskusstv/gl-05-rasprostranenie-sily' },
          { label: 'VI. Вращение по кругу', link: '/texts/sem-iskusstv/gl-06-vrashenie-po-krugu' },
          { label: 'VII. Умаление и прибыток', link: '/texts/sem-iskusstv/gl-07-umalenie-i-pribytok' },
          { label: 'VIII. Держаться оси', link: '/texts/sem-iskusstv/gl-08-derzhatsya-osi' },
          { label: 'IX. Управление изнутри', link: '/texts/sem-iskusstv/gl-09-upravlenie-iznutri' },
        ],
      },
      {
        label: 'Тридцать шесть стратагем', translations: { en: 'Thirty-Six Stratagems' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/36-stratagem' },
          { label: 'Стратагема 1', link: '/texts/36-stratagem/gl-01' },
          { label: 'Стратагема 2', link: '/texts/36-stratagem/gl-02' },
          { label: 'Стратагема 3', link: '/texts/36-stratagem/gl-03' },
          { label: 'Стратагема 4', link: '/texts/36-stratagem/gl-04' },
          { label: 'Стратагема 5', link: '/texts/36-stratagem/gl-05' },
          { label: 'Стратагема 6', link: '/texts/36-stratagem/gl-06' },
          { label: 'Стратагема 7', link: '/texts/36-stratagem/gl-07' },
          { label: 'Стратагема 8', link: '/texts/36-stratagem/gl-08' },
          { label: 'Стратагема 9', link: '/texts/36-stratagem/gl-09' },
          { label: 'Стратагема 10', link: '/texts/36-stratagem/gl-10' },
          { label: 'Стратагема 11', link: '/texts/36-stratagem/gl-11' },
          { label: 'Стратагема 12', link: '/texts/36-stratagem/gl-12' },
          { label: 'Стратагема 13', link: '/texts/36-stratagem/gl-13' },
          { label: 'Стратагема 14', link: '/texts/36-stratagem/gl-14' },
          { label: 'Стратагема 15', link: '/texts/36-stratagem/gl-15' },
          { label: 'Стратагема 16', link: '/texts/36-stratagem/gl-16' },
          { label: 'Стратагема 17', link: '/texts/36-stratagem/gl-17' },
          { label: 'Стратагема 18', link: '/texts/36-stratagem/gl-18' },
          { label: 'Стратагема 19', link: '/texts/36-stratagem/gl-19' },
          { label: 'Стратагема 20', link: '/texts/36-stratagem/gl-20' },
          { label: 'Стратагема 21', link: '/texts/36-stratagem/gl-21' },
          { label: 'Стратагема 22', link: '/texts/36-stratagem/gl-22' },
          { label: 'Стратагема 23', link: '/texts/36-stratagem/gl-23' },
          { label: 'Стратагема 24', link: '/texts/36-stratagem/gl-24' },
          { label: 'Стратагема 25', link: '/texts/36-stratagem/gl-25' },
          { label: 'Стратагема 26', link: '/texts/36-stratagem/gl-26' },
          { label: 'Стратагема 27', link: '/texts/36-stratagem/gl-27' },
          { label: 'Стратагема 28', link: '/texts/36-stratagem/gl-28' },
          { label: 'Стратагема 29', link: '/texts/36-stratagem/gl-29' },
          { label: 'Стратагема 30', link: '/texts/36-stratagem/gl-30' },
          { label: 'Стратагема 31', link: '/texts/36-stratagem/gl-31' },
          { label: 'Стратагема 32', link: '/texts/36-stratagem/gl-32' },
          { label: 'Стратагема 33', link: '/texts/36-stratagem/gl-33' },
          { label: 'Стратагема 34', link: '/texts/36-stratagem/gl-34' },
          { label: 'Стратагема 35', link: '/texts/36-stratagem/gl-35' },
          { label: 'Стратагема 36', link: '/texts/36-stratagem/gl-36' },
        ],
      },
      {
        label: 'Иньфу-цзин', translations: { en: 'Yinfu Jing' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/infu-czin' },
          { label: 'Введение', translations: { en: 'Introduction' }, link: '/texts/infu-czin/gl-vvedenie' },
          { label: 'Глава 1', link: '/texts/infu-czin/gl-glava-1' },
          { label: 'Глава 2', link: '/texts/infu-czin/gl-glava-2' },
          { label: 'Глава 3', link: '/texts/infu-czin/gl-glava-3' },
          { label: 'Приложение', translations: { en: 'Appendix' }, link: '/texts/infu-czin/gl-prilozhenie' },
        ],
      },
      {
        label: 'Книга Основ', translations: { en: 'Book of Foundations' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/kniga-osnov' },
          { label: 'I. Начало вещей', link: '/texts/kniga-osnov/gl-glava-1-nachalo-veshchey' },
          { label: 'II. Праведный Путь', link: '/texts/kniga-osnov/gl-glava-2-pravednyy-put' },
          { label: 'III. Воспитание воли', link: '/texts/kniga-osnov/gl-glava-3-vospitanie-voli' },
          { label: 'IV. Исконное совершенство', link: '/texts/kniga-osnov/gl-glava-4-iskonnoe-sovershenstvo' },
          { label: 'V. Почитание справедливости', link: '/texts/kniga-osnov/gl-glava-5-pochitanie-spravedlivosti' },
          { label: 'VI. Покой в ритуале', link: '/texts/kniga-osnov/gl-glava-6-pokoy-v-rituale' },
          { label: 'Комментарии', translations: { en: 'Commentary' }, link: '/texts/kniga-osnov/gl-kommentarii' },
        ],
      },
      {
        label: 'Три стратегии', translations: { en: 'Three Strategies' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/tri-strategii' },
          { label: 'Исследование', link: '/texts/tri-strategii/gl-issledovanie' },
          { label: 'Высшая стратегия', link: '/texts/tri-strategii/gl-vysshaya-strategiya' },
          { label: 'Срединная стратегия', link: '/texts/tri-strategii/gl-srednyaya-strategiya' },
          { label: 'Низшая стратегия', link: '/texts/tri-strategii/gl-nizshaya-strategiya' },
        ],
      },
      {
        label: 'Нэй-цзин (Су Вэнь)', translations: { en: 'Neijing (Su Wen)' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/su-wen' },
          { label: 'Раздел 1', link: '/texts/su-wen/gl-01' },
          { label: 'Раздел 2', link: '/texts/su-wen/gl-02' },
          { label: 'Раздел 3', link: '/texts/su-wen/gl-03' },
          { label: 'Раздел 4', link: '/texts/su-wen/gl-04' },
          { label: 'Раздел 6', link: '/texts/su-wen/gl-06' },
          { label: 'Раздел 7', link: '/texts/su-wen/gl-07' },
          { label: 'Раздел 8', link: '/texts/su-wen/gl-08' },
          { label: 'Раздел 9', link: '/texts/su-wen/gl-09' },
          { label: 'Раздел 10', link: '/texts/su-wen/gl-10' },
          { label: 'Раздел 11', link: '/texts/su-wen/gl-11' },
          { label: 'Раздел 13', link: '/texts/su-wen/gl-13' },
          { label: 'Раздел 14', link: '/texts/su-wen/gl-14' },
          { label: 'Раздел 15', link: '/texts/su-wen/gl-15' },
          { label: 'Раздел 16', link: '/texts/su-wen/gl-16' },
          { label: 'Раздел 17', link: '/texts/su-wen/gl-17' },
          { label: 'Раздел 18', link: '/texts/su-wen/gl-18' },
          { label: 'Раздел 19', link: '/texts/su-wen/gl-19' },
          { label: 'Раздел 20', link: '/texts/su-wen/gl-20' },
          { label: 'Раздел 22', link: '/texts/su-wen/gl-22' },
          { label: 'Раздел 23', link: '/texts/su-wen/gl-23' },
          { label: 'Раздел 24', link: '/texts/su-wen/gl-24' },
          { label: 'Раздел 25', link: '/texts/su-wen/gl-25' },
          { label: 'Раздел 26', link: '/texts/su-wen/gl-26' },
          { label: 'Раздел 27', link: '/texts/su-wen/gl-27' },
          { label: 'Раздел 28', link: '/texts/su-wen/gl-28' },
          { label: 'Раздел 29', link: '/texts/su-wen/gl-29' },
          { label: 'Раздел 30', link: '/texts/su-wen/gl-30' },
          { label: 'Раздел 31', link: '/texts/su-wen/gl-31' },
          { label: 'Раздел 32', link: '/texts/su-wen/gl-32' },
          { label: 'Раздел 33', link: '/texts/su-wen/gl-33' },
          { label: 'Раздел 34', link: '/texts/su-wen/gl-34' },
          { label: 'Раздел 35', link: '/texts/su-wen/gl-35' },
          { label: 'Раздел 36', link: '/texts/su-wen/gl-36' },
          { label: 'Раздел 37', link: '/texts/su-wen/gl-37' },
          { label: 'Раздел 38', link: '/texts/su-wen/gl-38' },
          { label: 'Раздел 39', link: '/texts/su-wen/gl-39' },
          { label: 'Раздел 40', link: '/texts/su-wen/gl-40' },
          { label: 'Раздел 41', link: '/texts/su-wen/gl-41' },
          { label: 'Раздел 42', link: '/texts/su-wen/gl-42' },
          { label: 'Раздел 43', link: '/texts/su-wen/gl-43' },
          { label: 'Раздел 44', link: '/texts/su-wen/gl-44' },
          { label: 'Раздел 45', link: '/texts/su-wen/gl-45' },
          { label: 'Раздел 46', link: '/texts/su-wen/gl-46' },
          { label: 'Раздел 47', link: '/texts/su-wen/gl-47' },
          { label: 'Раздел 48', link: '/texts/su-wen/gl-48' },
          { label: 'Раздел 49', link: '/texts/su-wen/gl-49' },
          { label: 'Раздел 50', link: '/texts/su-wen/gl-50' },
          { label: 'Раздел 51', link: '/texts/su-wen/gl-51' },
          { label: 'Раздел 52', link: '/texts/su-wen/gl-52' },
          { label: 'Раздел 53', link: '/texts/su-wen/gl-53' },
          { label: 'Раздел 54', link: '/texts/su-wen/gl-54' },
          { label: 'Раздел 55', link: '/texts/su-wen/gl-55' },
          { label: 'Раздел 56', link: '/texts/su-wen/gl-56' },
          { label: 'Раздел 57', link: '/texts/su-wen/gl-57' },
          { label: 'Раздел 58', link: '/texts/su-wen/gl-58' },
          { label: 'Раздел 59', link: '/texts/su-wen/gl-59' },
          { label: 'Раздел 60', link: '/texts/su-wen/gl-60' },
          { label: 'Раздел 61', link: '/texts/su-wen/gl-61' },
          { label: 'Раздел 62', link: '/texts/su-wen/gl-62' },
          { label: 'Раздел 63', link: '/texts/su-wen/gl-63' },
          { label: 'Раздел 64', link: '/texts/su-wen/gl-64' },
          { label: 'Раздел 65', link: '/texts/su-wen/gl-65' },
          { label: 'Раздел 66', link: '/texts/su-wen/gl-66' },
          { label: 'Раздел 67', link: '/texts/su-wen/gl-67' },
          { label: 'Раздел 68', link: '/texts/su-wen/gl-68' },
          { label: 'Раздел 69', link: '/texts/su-wen/gl-69' },
          { label: 'Раздел 70', link: '/texts/su-wen/gl-70' },
          { label: 'Раздел 71', link: '/texts/su-wen/gl-71' },
          { label: 'Раздел 74', link: '/texts/su-wen/gl-74' },
          { label: 'Раздел 75', link: '/texts/su-wen/gl-75' },
          { label: 'Раздел 76', link: '/texts/su-wen/gl-76' },
          { label: 'Раздел 77', link: '/texts/su-wen/gl-77' },
          { label: 'Раздел 78', link: '/texts/su-wen/gl-78' },
          { label: 'Раздел 79', link: '/texts/su-wen/gl-79' },
          { label: 'Раздел 80', link: '/texts/su-wen/gl-80' },
          { label: 'Раздел 81', link: '/texts/su-wen/gl-81' },
        ],
      },
      {
        label: 'Лин Шу (Ось духа)', translations: { en: 'Lingshu (Spiritual Pivot)' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/lin-shu' },
          { label: 'Предисловие', translations: { en: 'Foreword' }, link: '/texts/lin-shu/gl-00-predislovie' },
          { label: 'Раздел 1', link: '/texts/lin-shu/gl-01' },
          { label: 'Раздел 2', link: '/texts/lin-shu/gl-02' },
          { label: 'Раздел 3', link: '/texts/lin-shu/gl-03' },
          { label: 'Раздел 4', link: '/texts/lin-shu/gl-04' },
          { label: 'Раздел 5', link: '/texts/lin-shu/gl-05' },
          { label: 'Раздел 6', link: '/texts/lin-shu/gl-06' },
          { label: 'Раздел 7', link: '/texts/lin-shu/gl-07' },
          { label: 'Раздел 8', link: '/texts/lin-shu/gl-08' },
          { label: 'Раздел 9', link: '/texts/lin-shu/gl-09' },
          { label: 'Раздел 10', link: '/texts/lin-shu/gl-10' },
          { label: 'Раздел 11', link: '/texts/lin-shu/gl-11' },
          { label: 'Раздел 12', link: '/texts/lin-shu/gl-12' },
          { label: 'Раздел 13', link: '/texts/lin-shu/gl-13' },
          { label: 'Раздел 14', link: '/texts/lin-shu/gl-14' },
          { label: 'Раздел 15', link: '/texts/lin-shu/gl-15' },
          { label: 'Раздел 16', link: '/texts/lin-shu/gl-16' },
          { label: 'Раздел 17', link: '/texts/lin-shu/gl-17' },
          { label: 'Раздел 18', link: '/texts/lin-shu/gl-18' },
          { label: 'Раздел 19', link: '/texts/lin-shu/gl-19' },
          { label: 'Раздел 20', link: '/texts/lin-shu/gl-20' },
          { label: 'Раздел 21', link: '/texts/lin-shu/gl-21' },
          { label: 'Раздел 22', link: '/texts/lin-shu/gl-22' },
          { label: 'Раздел 23', link: '/texts/lin-shu/gl-23' },
          { label: 'Раздел 24', link: '/texts/lin-shu/gl-24' },
          { label: 'Раздел 25', link: '/texts/lin-shu/gl-25' },
          { label: 'Раздел 26', link: '/texts/lin-shu/gl-26' },
          { label: 'Раздел 27', link: '/texts/lin-shu/gl-27' },
          { label: 'Раздел 28', link: '/texts/lin-shu/gl-28' },
          { label: 'Раздел 29', link: '/texts/lin-shu/gl-29' },
          { label: 'Раздел 30', link: '/texts/lin-shu/gl-30' },
          { label: 'Раздел 31', link: '/texts/lin-shu/gl-31' },
          { label: 'Раздел 32', link: '/texts/lin-shu/gl-32' },
          { label: 'Раздел 33', link: '/texts/lin-shu/gl-33' },
          { label: 'Раздел 34', link: '/texts/lin-shu/gl-34' },
          { label: 'Раздел 35', link: '/texts/lin-shu/gl-35' },
          { label: 'Раздел 36', link: '/texts/lin-shu/gl-36' },
          { label: 'Раздел 37', link: '/texts/lin-shu/gl-37' },
          { label: 'Раздел 38', link: '/texts/lin-shu/gl-38' },
          { label: 'Раздел 39', link: '/texts/lin-shu/gl-39' },
          { label: 'Раздел 40', link: '/texts/lin-shu/gl-40' },
          { label: 'Раздел 41', link: '/texts/lin-shu/gl-41' },
          { label: 'Раздел 42', link: '/texts/lin-shu/gl-42' },
          { label: 'Раздел 43', link: '/texts/lin-shu/gl-43' },
          { label: 'Раздел 44', link: '/texts/lin-shu/gl-44' },
          { label: 'Раздел 45', link: '/texts/lin-shu/gl-45' },
          { label: 'Раздел 46', link: '/texts/lin-shu/gl-46' },
          { label: 'Раздел 47', link: '/texts/lin-shu/gl-47' },
          { label: 'Раздел 48', link: '/texts/lin-shu/gl-48' },
          { label: 'Раздел 49', link: '/texts/lin-shu/gl-49' },
          { label: 'Раздел 50', link: '/texts/lin-shu/gl-50' },
          { label: 'Раздел 51', link: '/texts/lin-shu/gl-51' },
          { label: 'Раздел 52', link: '/texts/lin-shu/gl-52' },
          { label: 'Раздел 53', link: '/texts/lin-shu/gl-53' },
          { label: 'Раздел 54', link: '/texts/lin-shu/gl-54' },
          { label: 'Раздел 55', link: '/texts/lin-shu/gl-55' },
          { label: 'Раздел 56', link: '/texts/lin-shu/gl-56' },
          { label: 'Раздел 57', link: '/texts/lin-shu/gl-57' },
          { label: 'Раздел 58', link: '/texts/lin-shu/gl-58' },
          { label: 'Раздел 59', link: '/texts/lin-shu/gl-59' },
          { label: 'Раздел 60', link: '/texts/lin-shu/gl-60' },
          { label: 'Раздел 61', link: '/texts/lin-shu/gl-61' },
          { label: 'Раздел 62', link: '/texts/lin-shu/gl-62' },
          { label: 'Раздел 63', link: '/texts/lin-shu/gl-63' },
          { label: 'Раздел 64', link: '/texts/lin-shu/gl-64' },
          { label: 'Раздел 65', link: '/texts/lin-shu/gl-65' },
          { label: 'Раздел 66', link: '/texts/lin-shu/gl-66' },
          { label: 'Раздел 67', link: '/texts/lin-shu/gl-67' },
          { label: 'Раздел 68', link: '/texts/lin-shu/gl-68' },
          { label: 'Раздел 69', link: '/texts/lin-shu/gl-69' },
          { label: 'Раздел 70', link: '/texts/lin-shu/gl-70' },
          { label: 'Раздел 71', link: '/texts/lin-shu/gl-71' },
          { label: 'Раздел 72', link: '/texts/lin-shu/gl-72' },
          { label: 'Раздел 73', link: '/texts/lin-shu/gl-73' },
          { label: 'Раздел 74', link: '/texts/lin-shu/gl-74' },
          { label: 'Раздел 75', link: '/texts/lin-shu/gl-75' },
          { label: 'Раздел 76', link: '/texts/lin-shu/gl-76' },
          { label: 'Раздел 77', link: '/texts/lin-shu/gl-77' },
          { label: 'Раздел 78', link: '/texts/lin-shu/gl-78' },
          { label: 'Раздел 79', link: '/texts/lin-shu/gl-79' },
          { label: 'Раздел 80', link: '/texts/lin-shu/gl-80' },
          { label: 'Раздел 81', link: '/texts/lin-shu/gl-81' },
        ],
      },
      {
        label: 'Чжоу И (Книга Перемен)', translations: { en: 'Zhou Yi (Book of Changes)' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/chzhou-i' },
          { label: 'Гексаграмма 1', link: '/texts/chzhou-i/gl-01' },
          { label: 'Гексаграмма 2', link: '/texts/chzhou-i/gl-02' },
          { label: 'Гексаграмма 3', link: '/texts/chzhou-i/gl-03' },
          { label: 'Гексаграмма 4', link: '/texts/chzhou-i/gl-04' },
          { label: 'Гексаграмма 5', link: '/texts/chzhou-i/gl-05' },
          { label: 'Гексаграмма 6', link: '/texts/chzhou-i/gl-06' },
          { label: 'Гексаграмма 7', link: '/texts/chzhou-i/gl-07' },
          { label: 'Гексаграмма 8', link: '/texts/chzhou-i/gl-08' },
          { label: 'Гексаграмма 9', link: '/texts/chzhou-i/gl-09' },
          { label: 'Гексаграмма 10', link: '/texts/chzhou-i/gl-10' },
          { label: 'Гексаграмма 11', link: '/texts/chzhou-i/gl-11' },
          { label: 'Гексаграмма 12', link: '/texts/chzhou-i/gl-12' },
          { label: 'Гексаграмма 13', link: '/texts/chzhou-i/gl-13' },
          { label: 'Гексаграмма 14', link: '/texts/chzhou-i/gl-14' },
          { label: 'Гексаграмма 15', link: '/texts/chzhou-i/gl-15' },
          { label: 'Гексаграмма 16', link: '/texts/chzhou-i/gl-16' },
          { label: 'Гексаграмма 17', link: '/texts/chzhou-i/gl-17' },
          { label: 'Гексаграмма 18', link: '/texts/chzhou-i/gl-18' },
          { label: 'Гексаграмма 19', link: '/texts/chzhou-i/gl-19' },
          { label: 'Гексаграмма 20', link: '/texts/chzhou-i/gl-20' },
          { label: 'Гексаграмма 21', link: '/texts/chzhou-i/gl-21' },
          { label: 'Гексаграмма 22', link: '/texts/chzhou-i/gl-22' },
          { label: 'Гексаграмма 23', link: '/texts/chzhou-i/gl-23' },
          { label: 'Гексаграмма 24', link: '/texts/chzhou-i/gl-24' },
          { label: 'Гексаграмма 25', link: '/texts/chzhou-i/gl-25' },
          { label: 'Гексаграмма 26', link: '/texts/chzhou-i/gl-26' },
          { label: 'Гексаграмма 27', link: '/texts/chzhou-i/gl-27' },
          { label: 'Гексаграмма 28', link: '/texts/chzhou-i/gl-28' },
          { label: 'Гексаграмма 29', link: '/texts/chzhou-i/gl-29' },
          { label: 'Гексаграмма 30', link: '/texts/chzhou-i/gl-30' },
          { label: 'Гексаграмма 31', link: '/texts/chzhou-i/gl-31' },
          { label: 'Гексаграмма 32', link: '/texts/chzhou-i/gl-32' },
          { label: 'Гексаграмма 33', link: '/texts/chzhou-i/gl-33' },
          { label: 'Гексаграмма 34', link: '/texts/chzhou-i/gl-34' },
          { label: 'Гексаграмма 35', link: '/texts/chzhou-i/gl-35' },
          { label: 'Гексаграмма 36', link: '/texts/chzhou-i/gl-36' },
          { label: 'Гексаграмма 37', link: '/texts/chzhou-i/gl-37' },
          { label: 'Гексаграмма 38', link: '/texts/chzhou-i/gl-38' },
          { label: 'Гексаграмма 39', link: '/texts/chzhou-i/gl-39' },
          { label: 'Гексаграмма 40', link: '/texts/chzhou-i/gl-40' },
          { label: 'Гексаграмма 41', link: '/texts/chzhou-i/gl-41' },
          { label: 'Гексаграмма 42', link: '/texts/chzhou-i/gl-42' },
          { label: 'Гексаграмма 43', link: '/texts/chzhou-i/gl-43' },
          { label: 'Гексаграмма 44', link: '/texts/chzhou-i/gl-44' },
          { label: 'Гексаграмма 45', link: '/texts/chzhou-i/gl-45' },
          { label: 'Гексаграмма 46', link: '/texts/chzhou-i/gl-46' },
          { label: 'Гексаграмма 47', link: '/texts/chzhou-i/gl-47' },
          { label: 'Гексаграмма 48', link: '/texts/chzhou-i/gl-48' },
          { label: 'Гексаграмма 49', link: '/texts/chzhou-i/gl-49' },
          { label: 'Гексаграмма 50', link: '/texts/chzhou-i/gl-50' },
          { label: 'Гексаграмма 51', link: '/texts/chzhou-i/gl-51' },
          { label: 'Гексаграмма 52', link: '/texts/chzhou-i/gl-52' },
          { label: 'Гексаграмма 53', link: '/texts/chzhou-i/gl-53' },
          { label: 'Гексаграмма 54', link: '/texts/chzhou-i/gl-54' },
          { label: 'Гексаграмма 55', link: '/texts/chzhou-i/gl-55' },
          { label: 'Гексаграмма 56', link: '/texts/chzhou-i/gl-56' },
          { label: 'Гексаграмма 57', link: '/texts/chzhou-i/gl-57' },
          { label: 'Гексаграмма 58', link: '/texts/chzhou-i/gl-58' },
          { label: 'Гексаграмма 59', link: '/texts/chzhou-i/gl-59' },
          { label: 'Гексаграмма 60', link: '/texts/chzhou-i/gl-60' },
          { label: 'Гексаграмма 61', link: '/texts/chzhou-i/gl-61' },
          { label: 'Гексаграмма 62', link: '/texts/chzhou-i/gl-62' },
          { label: 'Гексаграмма 63', link: '/texts/chzhou-i/gl-63' },
          { label: 'Гексаграмма 64', link: '/texts/chzhou-i/gl-64' },
        ],
      },
      {
        label: 'Чжоу Ли', translations: { en: 'Zhou Li' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/chzhou-li' },
          { label: 'Avertissement', link: '/texts/chzhou-li/book-00-avertissement' },
          { label: 'Введение', translations: { en: 'Introduction' }, link: '/texts/chzhou-li/book-00-introduction' },
          { label: 'Книга 1', link: '/texts/chzhou-li/book-01' },
            { label: 'Книга 2', link: '/texts/chzhou-li/book-02' },
            { label: 'Книга 3', link: '/texts/chzhou-li/book-03' },
            { label: 'Книга 4', link: '/texts/chzhou-li/book-04' },
            { label: 'Книга 5', link: '/texts/chzhou-li/book-05' },
            { label: 'Книга 6', link: '/texts/chzhou-li/book-06' },
            { label: 'Книга 7', link: '/texts/chzhou-li/book-07' },
            { label: 'Книга 8', link: '/texts/chzhou-li/book-08' },
            { label: 'Книга 9', link: '/texts/chzhou-li/book-09' },
            { label: 'Книга 10', link: '/texts/chzhou-li/book-10' },
            { label: 'Книга 11', link: '/texts/chzhou-li/book-11' },
            { label: 'Книга 12', link: '/texts/chzhou-li/book-12' },
            { label: 'Книга 13', link: '/texts/chzhou-li/book-13' },
            { label: 'Книга 14', link: '/texts/chzhou-li/book-14' },
            { label: 'Книга 15', link: '/texts/chzhou-li/book-15' },
            { label: 'Книга 16', link: '/texts/chzhou-li/book-16' },
            { label: 'Книга 17', link: '/texts/chzhou-li/book-17' },
            { label: 'Книга 18', link: '/texts/chzhou-li/book-18' },
            { label: 'Книга 19', link: '/texts/chzhou-li/book-19' },
            { label: 'Книга 20', link: '/texts/chzhou-li/book-20' },
            { label: 'Книга 21', link: '/texts/chzhou-li/book-21' },
            { label: 'Книга 22', link: '/texts/chzhou-li/book-22' },
            { label: 'Книга 23', link: '/texts/chzhou-li/book-23' },
            { label: 'Книга 24', link: '/texts/chzhou-li/book-24' },
            { label: 'Книга 25', link: '/texts/chzhou-li/book-25' },
            { label: 'Книга 26', link: '/texts/chzhou-li/book-26' },
            { label: 'Книга 27', link: '/texts/chzhou-li/book-27' },
            { label: 'Книга 28', link: '/texts/chzhou-li/book-28' },
            { label: 'Книга 29', link: '/texts/chzhou-li/book-29' },
            { label: 'Книга 30', link: '/texts/chzhou-li/book-30' },
            { label: 'Книга 31', link: '/texts/chzhou-li/book-31' },
            { label: 'Книга 32', link: '/texts/chzhou-li/book-32' },
            { label: 'Книга 33', link: '/texts/chzhou-li/book-33' },
            { label: 'Книга 34', link: '/texts/chzhou-li/book-34' },
            { label: 'Книга 35', link: '/texts/chzhou-li/book-35' },
            { label: 'Книга 36', link: '/texts/chzhou-li/book-36' },
            { label: 'Книга 37', link: '/texts/chzhou-li/book-37' },
            { label: 'Книга 38', link: '/texts/chzhou-li/book-38' },
            { label: 'Книга 39', link: '/texts/chzhou-li/book-39' },
            { label: 'Книга 40', link: '/texts/chzhou-li/book-40' },
            { label: 'Книга 41', link: '/texts/chzhou-li/book-41' },
            { label: 'Книга 42', link: '/texts/chzhou-li/book-42' },
            { label: 'Книга 43', link: '/texts/chzhou-li/book-43' },
            { label: 'Книга 44', link: '/texts/chzhou-li/book-44' },
          ],
          },
          {
          label: 'Шесть оберток (Лю Тао)', translations: { en: 'Six Secret Teachings (Liu Tao)' },
          collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/liu-tao' },
          { label: 'I. Учитель правителя Вэнь', link: '/texts/liu-tao/gl-01-uchitel-pravitelya-ven' },
          { label: 'II. Полнота и пустота', link: '/texts/liu-tao/gl-02-polnota-i-pustota' },
          { label: 'III. Дела государства', link: '/texts/liu-tao/gl-03-dela-gosudarstva' },
          { label: 'IV. Великие правила этикета', link: '/texts/liu-tao/gl-04-velikie-pravila-etiketa' },
          { label: 'V. Ясные указания', link: '/texts/liu-tao/gl-05-yasnye-ukazaniya' },
          { label: 'VI. Шесть хранителей', link: '/texts/liu-tao/gl-06-shest-hraniteley' },
          { label: 'VII. Сохранение территории государства', link: '/texts/liu-tao/gl-07-sohranenie-territorii-gosudarstva' },
          { label: 'VIII. Сохранение государства', link: '/texts/liu-tao/gl-08-sohranenie-gosudarstva' },
          { label: 'IX. Почитание достойных', link: '/texts/liu-tao/gl-09-pochitanie-dostoynyh' },
          { label: 'X. Выдвижение достойных', link: '/texts/liu-tao/gl-10-vydvizhenie-dostoynyh' },
          { label: 'XI. Награды и наказания', link: '/texts/liu-tao/gl-11-nagrady-i-nakazaniya' },
          { label: 'XII. Дао войны', link: '/texts/liu-tao/gl-12-dao-voyny' },
          { label: 'XIII. Начальные наставления', link: '/texts/liu-tao/gl-13-nachalnye-nastavleniya' },
          { label: 'XIV. Гражданские наставления', link: '/texts/liu-tao/gl-14-grazhdanskie-nastavleniya' },
          { label: 'XV. Гражданское наступление', link: '/texts/liu-tao/gl-15-grazhdanskoe-nastuplenie' },
          { label: 'XVI. Наставление о согласии с людьми', link: '/texts/liu-tao/gl-16-nastavlenie-o-soglasii-s-lyudmi' },
          { label: 'XVII. Три сомнения', link: '/texts/liu-tao/gl-17-tri-somneniya' },
          { label: 'XVIII. Крылья правителя', link: '/texts/liu-tao/gl-18-krylya-pravitelya' },
          { label: 'XIX. Обсуждение генералов', link: '/texts/liu-tao/gl-19-obsuzhdenie-generalov' },
          { label: 'XX. Отбор командиров', link: '/texts/liu-tao/gl-20-otbor-komandirov' },
          { label: 'XXI. Назначение генерала', link: '/texts/liu-tao/gl-21-naznachenie-generala' },
          { label: 'XXII. Воодушевление армии', link: '/texts/liu-tao/gl-22-voodushevlenie-armii' },
          { label: 'XXIII. Секретные бирки', link: '/texts/liu-tao/gl-23-sekretnye-birki' },
          { label: 'XXIV. Секретные письма', link: '/texts/liu-tao/gl-24-sekretnye-pisma' },
          { label: 'XXV. Стратегическая сила армии', link: '/texts/liu-tao/gl-25-strategicheskaya-sila-armii' },
          { label: 'XXVI. Необычная армия', link: '/texts/liu-tao/gl-26-neobychnaya-armiya' },
          { label: 'XXVII. Пять звуков', link: '/texts/liu-tao/gl-27-pyat-zvukov' },
          { label: 'XXVIII. Признаки армии', link: '/texts/liu-tao/gl-28-priznaki-armii' },
          { label: 'XXIX. Хозяйственные принадлежности и утварь', link: '/texts/liu-tao/gl-29-hozyaystvennye-prinadlezhnosti-i-utvar' },
          { label: 'XXX. Снаряжение армии', link: '/texts/liu-tao/gl-30-snaryazhenie-armii' },
          { label: 'XXXI. Три развертывания', link: '/texts/liu-tao/gl-31-tri-razvertyvaniya' },
          { label: 'XXXII. Безотлагательные сражения', link: '/texts/liu-tao/gl-32-bezotlagatelnye-srazheniya' },
          { label: 'XXXIII. Решительное отступление', link: '/texts/liu-tao/gl-33-reshitelnoe-otstuplenie' },
          { label: 'XXXIV. Планирование для армии', link: '/texts/liu-tao/gl-34-planirovanie-dlya-armii' },
          { label: 'XXXV. Приближение к границе', link: '/texts/liu-tao/gl-35-priblizhenie-k-granitse' },
          { label: 'XXXVI. Движение и отдых', link: '/texts/liu-tao/gl-36-dvizhenie-i-otdyh' },
          { label: 'XXXVII. Гонги и барабаны', link: '/texts/liu-tao/gl-37-gongi-i-barabany' },
          { label: 'XXXVIII. Отрезанные пути', link: '/texts/liu-tao/gl-38-otrezannye-puti' },
          { label: 'XXXIX. Захват вражеской территории', link: '/texts/liu-tao/gl-39-zahvat-vrazheskoy-territorii' },
          { label: 'XL. Огневая война', link: '/texts/liu-tao/gl-40-ognevaya-voyna' },
          { label: 'XLI. Пустые укрепления', link: '/texts/liu-tao/gl-41-pustye-ukrepleniya' },
          { label: 'XLII. Война в лесу', link: '/texts/liu-tao/gl-42-voyna-v-lesu' },
          { label: 'XLIII. Бурная и быстрая сила', link: '/texts/liu-tao/gl-43-burnaya-i-bystraya-sila' },
          { label: 'XLIV. Сильный враг', link: '/texts/liu-tao/gl-44-silnyy-vrag' },
          { label: 'XLV. Воинственный враг', link: '/texts/liu-tao/gl-45-voinstvennyy-vrag' },
          { label: 'XLVI. Боевые порядки «Вороны и облака» в горах', link: '/texts/liu-tao/gl-46-boevye-poryadki-vorony-i-oblaka-v-gorah' },
          { label: 'XLVII. Боевые порядки «Вороны и облака» в болоте', link: '/texts/liu-tao/gl-47-boevye-poryadki-vorony-i-oblaka-v-bolote' },
          { label: 'XLVIII. Малые и большие', link: '/texts/liu-tao/gl-48-malye-i-bolshie' },
          { label: 'XLIX. Разделение долины', link: '/texts/liu-tao/gl-49-razdelenie-doliny' },
          { label: 'L. Рассредоточение и соединение', link: '/texts/liu-tao/gl-50-rassredotochenie-i-soedinenie' },
          { label: 'LI. Боевой головной отряд', link: '/texts/liu-tao/gl-51-boevoy-golovnoy-otryad' },
          { label: 'LII. Отбор воинов', link: '/texts/liu-tao/gl-52-otbor-voinov' },
          { label: 'LIII. Обучение бою', link: '/texts/liu-tao/gl-53-obuchenie-boyu' },
          { label: 'LIV. Равные силы', link: '/texts/liu-tao/gl-54-ravnye-sily' },
          { label: 'LV. Воины на боевых колесницах', link: '/texts/liu-tao/gl-55-voiny-na-boevyh-kolesnitsah' },
          { label: 'LVI. Воины боевой конницы', link: '/texts/liu-tao/gl-56-voiny-boevoy-konnitsy' },
          { label: 'LVII. Колесницы в битве', link: '/texts/liu-tao/gl-57-kolesnitsy-v-bitve' },
          { label: 'LVIII. Конница в битве', link: '/texts/liu-tao/gl-58-konnitsa-v-bitve' },
          { label: 'LIX. Пешие воины в битве', link: '/texts/liu-tao/gl-59-peshie-voiny-v-bitve' },
        ],
      },
      {
        label: '10 крыльев', translations: { en: 'Ten Wings' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/10-krylev' },
        ],
      },
      {
        label: 'Книга Песен', translations: { en: 'Book of Songs' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/kniga-pesen' },
        ],
      },
      {
        label: 'Книга Преданий', translations: { en: 'Book of Documents' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/kniga-predaniy' },
        ],
      },
      {
        label: 'Пять явлений', translations: { en: 'Five Phenomena' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/pyat-yavleniy' },
        ],
      },
      {
        label: 'Рождение Дао', translations: { en: 'Birth of Dao' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/rozhdenie-dao' },
        ],
      },
      {
        label: 'Обозначение Дао', translations: { en: 'Naming of Dao' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/oboznachenie-dao' },
        ],
      },
      {
        label: '9 Императоров', translations: { en: 'Nine Emperors' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/9-imperatorov' },
        ],
      },
      {
        label: 'Знак Инь Ян', translations: { en: 'Yin Yang Sign' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/znak-in-yan' },
        ],
      },
      {
        label: 'Компас Ло Пань', translations: { en: 'Luopan Compass' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/kompas-lo-pan' },
        ],
      },
      {
        label: 'Форма Основа', translations: { en: 'Form and Foundation' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/forma-osnova' },
        ],
      },
      {
        label: 'Игра Го', translations: { en: 'Game of Go' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/igra-go' },
        ],
      },
      {
        label: 'Игра И', translations: { en: 'Game of Yi' },
        collapsed: true,
        items: [
          { label: 'Обзор', translations: { en: 'Overview' }, link: '/texts/igra-i' },
        ],
      },
    ],
    social: [
      { icon: 'github', label: 'GitHub', href: 'https://github.com/great-foundation-pro/doc-pathofstrategy' },
    ],
  }), ...astroEmbed(), mdx(), partytown(), analyticsIntegration()],

  vite: {
    plugins: [tailwindcss()],
  },
});